# Generated by Django 3.1.4 on 2021-01-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartphoneDetail',
        ),
    ]
