# Generated by Django 3.1.4 on 2021-01-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0003_smartphonedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphonedetail',
            old_name='smartphone',
            new_name='smartphone_id',
        ),
    ]
