# Generated by Django 3.1.4 on 2021-01-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0004_auto_20210123_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphonedetail',
            old_name='smartphone_id',
            new_name='smartphone',
        ),
    ]
