# Generated by Django 3.1.4 on 2021-01-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0005_auto_20210123_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='image1',
            field=models.ImageField(null=True, upload_to='img/smartphone/'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image2',
            field=models.ImageField(null=True, upload_to='img/smartphone/'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image3',
            field=models.ImageField(null=True, upload_to='img/smartphone/'),
        ),
    ]
