# Generated by Django 3.1.4 on 2021-01-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0007_auto_20210123_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(null=True, upload_to='img/smartphone/'),
        ),
    ]
