# Generated by Django 3.1.4 on 2021-01-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0008_smartphone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='image1s',
            field=models.ImageField(null=True, upload_to='img/smartphone/'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image2s',
            field=models.ImageField(null=True, upload_to='img/smartphone/'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image3s',
            field=models.ImageField(null=True, upload_to='img/smartphone/'),
        ),
    ]
