# Generated by Django 3.1.4 on 2021-01-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0009_auto_20210123_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphonedetail',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10),
        ),
    ]
