# Generated by Django 3.1.4 on 2021-02-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0015_laptop_laptopdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(null=True, upload_to='img/laptop/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image1',
            field=models.ImageField(null=True, upload_to='img/laptop/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image1s',
            field=models.ImageField(null=True, upload_to='img/laptop/'),
        ),
    ]
