# Generated by Django 3.1.4 on 2021-02-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0016_auto_20210204_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaptopDetail',
        ),
    ]
