# Generated by Django 3.1.4 on 2021-04-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0019_auto_20210331_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartwatch',
            name='smartwatch_id',
        ),
        migrations.RemoveField(
            model_name='smartwatchdetail',
            name='smartwatch',
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
