# Generated by Django 3.1.4 on 2021-04-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0020_auto_20210423_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartwatchdetail',
            name='smartwatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gadget.smartwatch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
