# Generated by Django 3.1.4 on 2021-04-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0021_auto_20210423_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartwatchDetail',
        ),
    ]
