# Generated by Django 3.1.4 on 2021-04-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0024_smartphonedetail1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartphoneDetail1',
        ),
    ]
