# Generated by Django 3.1.4 on 2021-01-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210123_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileimage',
            field=models.ImageField(blank=True, upload_to='static/img/user/'),
        ),
    ]
