# Generated by Django 3.1.4 on 2021-01-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
