# Generated by Django 3.1.4 on 2021-04-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartphoneDetail1',
        ),
    ]
